/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuuu_ipcamera_IPCAM */

#ifndef _Included_com_liuuu_ipcamera_IPCAM
#define _Included_com_liuuu_ipcamera_IPCAM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuuu_ipcamera_IPCAM
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_liuuu_ipcamera_IPCAM_startRTSPServer
  (JNIEnv *, jobject);

/*
 * Class:     com_liuuu_ipcamera_IPCAM
 * Method:    helloWorld
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liuuu_ipcamera_IPCAM_helloWorld
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
